version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sap-doc-postgres
    environment:
      POSTGRES_DB: sap_doc_app
      POSTGRES_USER: kade
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sap-doc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kade -d sap_doc_app"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sap-doc-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sap_doc_app
      DB_USER: kade
      DB_PASSWORD: password123
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sap-doc-network
    command: sh -c "npm run migrate && npm run dev"

  # Google ADK Scheduling Assistant
  adk-service:
    build:
      context: ./adk-service
      dockerfile: Dockerfile
    container_name: sap-doc-adk
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sap_doc_app
      DB_USER: kade
      DB_PASSWORD: password123
      HOST: 0.0.0.0
      PORT: 8000
      ENVIRONMENT: development
      # Required: Add your Google API key for ADK
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./adk-service:/app
    networks:
      - sap-doc-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sap-doc-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - sap-doc-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001/api

volumes:
  postgres_data:

networks:
  sap-doc-network:
    driver: bridge
